blog/urls.py
from django.urls import path,re_path
from . import views

app_name = "blog"
urlpatterns = [
    path("",views.index,name="index"),
    path("<int:blog_id>",views.detail,name="detail"),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("portfolio.urls")),
    path('blog/', include("blog.urls")),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
    path("",views.index,name="index"),
    path("myportfolio/",views.allportfolio,name="allportfolio"),
    path("<int:portfolio_id>",views.detail,name="detail"),
]

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.
class Blogs(models.Model):
    title = models.CharField(max_length=200)
    description = RichTextField()
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.
class Portfolio_Project(models.Model):
    title = models.CharField(max_length=200)
    description = RichTextField()
    image = models.ImageField(upload_to='images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blogs
# Create your views here.

def index(request):
    allblog = Blogs.objects.all()
    context = {
        "allblog":allblog,
    }
    return render(request,"blog/all_blogs.html",context)

def detail(request,blog_id):
    blog = get_object_or_404(Blogs,pk=blog_id)
    context = {
        "blog": blog,
    }
    return render(request, "blog/detail.html", context)

portfolio/views.py
from django.shortcuts import render,get_object_or_404
from .models import Portfolio_Project
# Create your views here.
def index(request):
    projects = Portfolio_Project.objects.order_by('-id')[:4]
    context = {
        "projects":projects,
    }
    return render(request,"portfolio/index.html",context)

def allportfolio(request):
    all = Portfolio_Project.objects.order_by('-id')
    context = {
        "all":all,
    }
    return render(request,"portfolio/all_portfolio.html",context)

def detail(request,portfolio_id):
    portfolioInfo = get_object_or_404(Portfolio_Project,pk=portfolio_id)
    context = {
        "portfolioInfo":portfolioInfo,
    }
    return render(request, "portfolio/detail.html", context)

temp/templates/blog/all_blogs.html
{% extends 'shared/main.html' %}
{% load static %}
{% block title %}
    Blogs
{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h2 class="alert alert-info text-center" style="width:22%;margin:10px;">
            Number Of Blog{{ allblog.count|pluralize }}: {{ allblog.count }}
        </h2>
        <div class="row">
            {% for blog in allblog %}
                <div class="col-md-12 col-xs-12">
                    <a href="{% url 'blog:detail' blog.id %}" class="detailbloglink">
                        <div class="blogcart">
                            <h2>{{ blog.title }}</h2>
                            <p>{{ blog.description|truncatechars:450|striptags }}</p>
                            <p>{{ blog.date|date:'M d Y'|upper }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

temp/templates/blog/detail.html
{% extends 'shared/main.html' %}
{% load static %}
{% block title %}
    Blogs - Detail
{% endblock %}

{% block body %}
    <div class="container">
        <div class="blogdetail">
            <h2 class="text-center">{{ blog.title }}</h2>
            <p>{{ blog.description|safe }}</p>
            <p style="color:#48b500;">{{ blog.date|date:'M d Y'|upper }}</p>
        </div>
    </div>
{% endblock %}

temp/templates/include/footer.html
<!-- Footer -->
<footer class="page-footer font-small">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://academyatlas.ir/" style="outline:none;"> AcademyAtlas.ir</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

temp/templates/include/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'portfolio:index' %}" style="outline:none;">Home</a>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a href="#" class="nav-link" style="outline:none;">Resumeh</a>
      </li>
      <li>
        <a href="{% url 'blog:index' %}" class="nav-link btn btn-warning">Blog</a>
      </li>
    </ul>
  </div>
</nav>

temp/templates/portfolio/all_portfolio.html
{% extends 'shared/main.html' %}
{% load static %}
{% block title %}
    All My PortFolio
{% endblock %}

{% block body %}
    <div align="center">
        <div class="portfolio-titr">
        <h2>
            All My PortFolio
        </h2>
    </div>
    </div>
    <br>
    <div align="center">
        <div class="allportfolio-carts">
            <div class="row">
                {% for portfolio in all %}
                    <div class="col-md-3 col-xs-12">
                        <a href="{% url 'portfolio:detail' portfolio.id %}" class="linkBgCart">
                            <div class="bgcart">
                                <img src="../media/{{ portfolio.image }}">
                                <h4>{{ portfolio.title }}</h4>
                                <hr style="width:50%;">
                                <p>{{ portfolio.description|truncatechars:100|striptags }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

temp/templates/portfolio/detail.html
{% extends 'shared/main.html' %}
{% load static %}
{% block title %}
    PortFolio - Detail
{% endblock %}

{% block body %}
    <div class="container">
        <div class="blogdetail">
            <h2 class="text-center">{{ portfolioInfo.title }}</h2>
            <p>{{ portfolioInfo.description|safe }}</p>
        </div>
    </div>
{% endblock %}

temp/templates/portfolio/index.html
{% extends 'shared/main.html' %}
{% load static %}
{% block title %}
    PortFolio
{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="text-center">
            <h1 class="portfolio-h1-title">
                ** Arman.Coder **
            </h1>
            <img class="portfolio-image" src="{% static 'images/27698.jpg' %}" alt="" width="500">
        </div>
        <br>
        <div align="center">
            <div class="portfolio-titr">
            <h2>
                PortFolio
            </h2>
        </div>
        </div>
        <br>
        <div align="center">
            <div class="allportfolio-carts">
                <div class="row">
                    {% for project in projects %}
                        <div class="col-md-3 col-xs-12">
                            <a href="{% url 'portfolio:detail' project.id %}" class="linkBgCart">
                                <div class="bgcart">
                                    <img src="media/{{ project.image }}">
                                    <h4>{{ project.title }}</h4>
                                    <hr style="width:50%;">
                                    <p>{{ project.description|striptags|truncatechars:100 }}</p>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
                <a href="{% url 'portfolio:allportfolio' %}" class="btn btn-success allMyPortfolio">See All My Portfolio</a>
            </div>
        </div>
    </div>
{% endblock %}

temp/templates/shared/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
{% include 'include/navbar.html' %}

{% block body %}
{% endblock %}

{% include 'include/footer.html' %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>